### ISSUE TITLE
PDF Scale or DPI Metadata ignored on PDF creation

### ISSUE THREAD

**Issue by acsr** [zopyx/zopyx.smartprintng.plone#1]
I am using the online demo with the picture http://demo.produce-and-publish.com/demo-project/contents/leitlinie/tmpUSvjSc.jpeg/view
### Create an unchanged reference PDF
- Go to http://demo.produce-and-publish.com/demo-project/conversions/leitlinie
- Do an unchanged conversion by clicking "Generate PDF"
- Download the PDF

Result: All default images are unscaled and exceed the boundaries of the layout. (Hint: The default DPI value of the image extracted from the PDF is 96.)
### Change the DPI-Metadata of the image
- Download the image
- Change the DPI setting to 300DPI. that results in a width of around 145mm, that matches the size of the body text area in the PDF.
- Check if the image values were changed!
- Go to http://demo.produce-and-publish.com/demo-project/conversions/leitlinie
- Do an conversion without changing parameters by clicking "Generate PDF"
- Download the new PDF

Result: unchanged PDF. The DPI value of the image extracted from the PDF is still 96!
### Change the PDF scaling settings of the image
- Download the image
- Change the Scale setting in the PDF tab to 30%.
- Check if the image values were changed!
- Go to http://demo.produce-and-publish.com/demo-project/conversions/leitlinie
- Go to to the image inspector and check if the scale of the above image is changed to 30% in this context.
- Do an conversion without changing parameters by clicking "Generate PDF"
- Download the new PDF

Result: unchanged PDF. The DPI value of the image extracted from the PDF is still 96!
## Suggestions:

Add an option to interpret the X/Y DPI metadata settings and maybe convert it into the PDF scale as well.
The DPI metadata is the standard way to define the default size of an image in the print industry. Even it is not necessary corresponding to the size usual intended by a non professional user, it is the the simplest way to prepare images for publication in an distributed workflow since decades. 
### Drawbacks:

The option may be misleading in the case of reuse of the same picture in different sizes in different context. But nevertheless it is useful to have this option due to the other drawback that the same image in different context may need different resolution or a different caption as well.
### Offline Workflow / Import

For batch processing a naming convention that carries the size in the filename can be a solution as well. Naming conventions for images are a common use case during offline collection by the editor or author.

**Comment by zopyx** [comment]
Outdated
